[project]
name = "duck-dbt-carsales"
version = "0.1.0"
description = "duck 4 fun"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9.3",
    "dbt-duckdb>=1.5.2",
    "duckdb>=1.2.1",
    "plotly>=6.0.1",
    "streamlit>=1.44.0",
]
